[package]
name = "brainrust"
version = "0.1.0"
authors = ["Deadbeef <fee1-dead-beef@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
